logging:
  level:
    root: info
    org.hiberante.SQL: debug
    org.hiberante.type: trace

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://175.120.95.229:5432/postgres
    username: achacha
    password: achacha12#$

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: update
